<?php

namespace Marca\CalendarBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CalendarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalendarRepository extends EntityRepository
{
}