<?php

namespace Marca\AssessmentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AssessmentsetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssessmentsetRepository extends EntityRepository
{

    
}
