<?php

namespace Marca\AssessmentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RatingsetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RatingsetRepository extends EntityRepository
{
    public function ratingsetsByPortfolioset($portfolioset)
    {
       return $this->getEntityManager()
               ->createQuery('SELECT r from MarcaAssessmentBundle:Ratingset r WHERE r.portfolioset = ?1')
               ->setParameters(array('1' => $portfolioset))->getResult();
    }
}
