<?php

namespace Marca\AssessmentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RatingsetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RatingsetRepository extends EntityRepository
{
    public function ratingsetByUser($user,$course,$rater)
    {
       return $this->getEntityManager()
               ->createQuery('SELECT r from MarcaAssessmentBundle:Ratingset r WHERE r.course = ?1 AND r.user = ?2 AND r.rater = ?3')
               ->setParameters(array('1' => $course,'2' => $user,'3' => $rater))->getResult();
    }
}
