<?php

namespace Marca\AssessmentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ScaleitemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScaleitemRepository extends EntityRepository
{
}
