imports:
    - { resource: config.yml }

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug

framework:
    router:
      resource: "%kernel.root_dir%/config/routing_cas.yml"

security:
    firewalls:
        main:
            pattern: ^/
            logout:
                path:   /logout
                target: /
            trusted_sso:
                manager: admin_sso
                create_users: true
                created_users_roles: [ROLE_USER, ROLE_ADMIN]
                login_action: BeSimpleSsoAuthBundle:TrustedSso:login
                logout_action: BeSimpleSsoAuthBundle:TrustedSso:logout
            provider: fos_userbundle
            anonymous:    true
            switch_user: true