# app/config/fileSystem.yml

knp_gaufrette:
    adapters:
        uploads:
            amazon_s3:
                amazon_s3_id: ct_file_store.s3
                bucket_name: %s3_bucket_name%
                options:
                    create: true

    filesystems:
        amazon_s3:
            adapter:    uploads
            
    stream_wrapper: ~

