# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    marca_user_registration:
        class: Marca\UserBundle\Form\UserType
        arguments: ["fos_user.model.user.class"]
        tags:
                    - { name: form.type }
    sso_user_provider:
        class: Marca\UserBundle\Security\SSOUserProvider
        arguments:
            - '@fos_user.user_manager'
            - '@doctrine.orm.entity_manager'
            - '@fos_user.util.token_generator'
    course_path_twig_extension:
        class: Marca\CourseBundle\Twig\CourseExtension
        arguments:
            - '@service_container'
            - '@request_stack'
        tags:
                - { name: twig.extension }

    directory_namer.upload_file:
        class: Marca\FileBundle\Namer\DirectoryNamer
        public: true
        tags:
            - { name: directory_namer }

    vich_uploader.namer_origname.property_file:
        class: Vich\UploaderBundle\Naming\OrignameNamer
        public: true
