<?php

namespace Marca\AssignmentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AssignmentSubmissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssignmentSubmissionRepository extends EntityRepository
{
}
