<?php

namespace Marca\AssignmentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AssignmentSubmissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssignmentSubmissionRepository extends EntityRepository
{

    /**
     * Finds submissions for all stages of the given assignment, by user
     * @param $user
     * @param $assignment
     * @return array
     */
    public function findSubmissionsForUser($user, $assignment)
    {

       return   $this->getEntityManager()
                ->createQuery('SELECT s from MarcaAssignmentBundle:AssignmentSubmission s JOIN s.stage a WHERE s.user = ?1 AND a.assignment = ?2')
                ->setParameters(array('1' => $user, '2' => $assignment))->getResult();

    }

}

