<?php

namespace Marca\JournalBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * JournalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JournalRepository extends EntityRepository
{
  public function findJournalRecent($user, $course, $set)
    {  
       $offset = $set * 5;
       return $this->getEntityManager()
               ->createQuery('SELECT j from MarcaJournalBundle:Journal j WHERE j.user = ?1 AND j.course = ?2 ORDER BY j.updated DESC')
               ->setParameters(array('1' => $user, '2' => $course))->setMaxResults(5)->setFirstResult($offset)->getResult();
    }
}