<?php

namespace Marca\JournalBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * JournalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JournalRepository extends EntityRepository
{
  public function findJournalRecent($user, $course)
    {  
       return $this->getEntityManager()
               ->createQuery('SELECT j from MarcaJournalBundle:Journal j WHERE j.user = ?1 AND j.course = ?2 ORDER BY j.created DESC')
               ->setParameters(array('1' => $user, '2' => $course))->getResult();
    }
    
  public function countJournalsByUser($user, $course)
    {  
       return $this->getEntityManager()
               ->createQuery('SELECT j from MarcaJournalBundle:Journal j WHERE j.user = ?1 AND j.course = ?2')
               ->setParameters(array('1' => $user, '2' => $course))->getResult();
    }  

  public function countJournalsByCourse($course)
    {  
       return $this->getEntityManager()
               ->createQuery('SELECT j from MarcaJournalBundle:Journal j WHERE j.course = ?1')
               ->setParameters(array('1' => $course))->getResult();
    }    
}