<?php

namespace Marca\JournalBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * JournalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JournalRepository extends EntityRepository
{
  public function findJournalRecent($userid, $courseid, $set)
    {  
       $offset = $set * 5;
       return $this->getEntityManager()
               ->createQuery('SELECT j from MarcaJournalBundle:Journal j WHERE j.userid = ?1 AND j.courseid = ?2 ORDER BY j.updated DESC')
               ->setParameters(array('1' => $userid, '2' => $courseid))->setMaxResults(5)->setFirstResult($offset)->getResult();
    }
}