<?php

namespace Marca\GradebookBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GradesetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GradesetRepository extends EntityRepository
{
    public function findByCourse($courseid)
    {
        return $this->getEntityManager()
            ->createQuery("SELECT g from MarcaGradebookBundle:Gradeset g join g.course c WHERE c.id = ?1")
            ->setParameters(array('1' => $courseid))->getResult();
    }
}
