<?php

namespace Marca\DocBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MarkupsetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarkupsetRepository extends EntityRepository
{
}
