<?php

namespace Marca\DocBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MarkupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarkupRepository extends EntityRepository
{
    public function findMarkupByUser($user)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT m from MarcaDocBundle:Markup m JOIN m.markupset s WHERE s.owner = ?1 ORDER BY m.name')->setParameter('1',$user)->getResult();
    }
    
     public function findMarkupByCourse($course)
             {
        return $this->getEntityManager()
                ->createQuery('SELECT m from MarcaDocBundle:Markup m JOIN m.markupset s JOIN s.courses c where c.id = ?1')->setParameter('1',$course)->getResult();
    }    
}