<?php

namespace Marca\DocBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TrackingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrackingRepository extends EntityRepository
{

    public function countMarkup()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT t.id,m.name,count(t.id)as mcount FROM MarcaDocBundle:Tracking t JOIN t.markup m GROUP BY t.markup')->getResult();
    }


}
