<?php

namespace Marca\PortfolioBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PortitemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PortitemRepository extends EntityRepository
{
    public function findByPortset($portset)
    {  
       return $this->getEntityManager()
               ->createQuery('SELECT p from MarcaPortfolioBundle:Portitem p JOIN p.portset o WHERE o.id = ?1 ORDER BY p.sortorder ASC')
               ->setParameter('1',$portset)->getResult();
    }
}