<?php

namespace Marca\PortfolioBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PortitemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PortitemRepository extends EntityRepository
{
}