<?php

namespace Marca\PortfolioBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PortfoliosetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PortfoliosetRepository extends EntityRepository
{
    public function findByUser($user,$course)
    {  
       return $this->getEntityManager()
               ->createQuery('SELECT s,p from MarcaPortfolioBundle:Portfolioset s JOIN s.portfolioitems p WHERE s.user = ?1 AND s.course = ?2')
               ->setParameter('1',$user)->setParameter('2',$course)->getSingleResult();
    }  
}
