<?php

namespace Marca\PortfolioBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PortfoliosetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PortfoliosetRepository extends EntityRepository
{
    public function findByUser($user,$course)
    {  
       return $this->getEntityManager()
               ->createQuery('SELECT p from MarcaPortfolioBundle:Portfolioset p  WHERE p.user = ?1 AND p.course = ?2 AND p.port_default=TRUE')
               ->setParameter('1',$user)->setParameter('2',$course)->setMaxResults(1)->getResult();
    } 
         
}
