<?php

namespace Marca\ForumBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    public function countCommentsByUser($user, $course)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT c.id FROM MarcaForumBundle:Comment c JOIN c.forum f  WHERE c.user = ?1 AND f.course = ?2')
                ->setParameters(array('1' => $user, '2' => $course))->getResult();
    } 
    
}