<?php

namespace Marca\ForumBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    public function countCommentsByUser($user)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT f.id FROM MarcaForumBundle:Comment f WHERE f.user = ?1')->setParameter('1',$user)->getResult();
    } 
    
}