<?php

namespace Marca\ForumBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ForumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForumRepository extends EntityRepository
{
    public function findForumRecent($user, $set)
    {  
       $offset = $set * 5;
       return $this->getEntityManager()
               ->createQuery('SELECT f from MarcaForumBundle:Forum f ORDER BY f.created DESC')
               ->setMaxResults(5)->setFirstResult($offset)->getResult();
    }
}