<?php

namespace Marca\ForumBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ForumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForumRepository extends EntityRepository
{
    public function findForumRecent($user)
    {  
       return $this->getEntityManager()
               ->createQuery('SELECT f from MarcaForumBundle:Forum f ORDER BY f.created DESC')
               ->getResult();
    }
}