<?php

namespace Marca\ForumBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReplyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReplyRepository extends EntityRepository
{
    public function countRepliesByUser($user)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT f.id FROM MarcaForumBundle:Reply f WHERE f.user = ?1')->setParameter('1',$user)->getResult();
    } 
    
}