<?php

namespace Marca\TagBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TagsetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagsetRepository extends EntityRepository
{
    public function findTagsetByUser($user)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT t from MarcaTagBundle:Tagset t WHERE t.user = ?1 OR t.shared=1 ORDER BY t.shared,t.name')->setParameter('1',$user)->getResult();
    }

    public function findResourcesTagsetByCourse($course, $parents)
    {
        return $this->createQueryBuilder('s')
            ->join('s.tag','t')
            ->join('s.course', 'c')
            ->select('t.color,t.name,t.sort')
            ->where('c.id IN(:parents) or c.id = :course')
            ->setParameter('course', $course)
            ->setParameter('parents', $parents)
            ->orderBy('t.sort','ASC')
            ->addOrderBy('t.name','ASC')
            ->getQuery()
            ->getResult();

    }


    public function findTagsetByCourse($course)
    {
        return $this->createQueryBuilder('s')
            ->join('s.tag','t')
            ->join('s.course', 'c')
            ->select('t.color,t.name,t.sort')
            ->where('c.id = :course')
            ->setParameter('course', $course)
            ->orderBy('t.sort','ASC')
            ->addOrderBy('t.name','ASC')
            ->getQuery()
            ->getResult();
    }
    
    public function findSystemTags()
    {  
       return $this->getEntityManager()
               ->createQuery('SELECT t from MarcaTagBundle:Tag t WHERE t.systemtag = 1')
               ->getResult();
    }

    public function findDefault()
    {  
       return $this->getEntityManager()
               ->createQuery('SELECT t from MarcaTagBundle:Tagset t WHERE t.shared = 2')
               ->getResult();
    }
    
}