<?php

namespace Marca\TagBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TagsetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagsetRepository extends EntityRepository
{
}