<?php

namespace Marca\TagBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TagsetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagsetRepository extends EntityRepository
{
    public function findTagsetByUser($user)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT t from MarcaTagBundle:Tagset t WHERE t.user = ?1 OR t.shared=1 ORDER BY t.shared,t.name')->setParameter('1',$user)->getResult();
    } 
    
    public function findTagsetIdByCourse($courseid)
    {  
       return $this->getEntityManager()
               ->createQuery('SELECT t from MarcaTagBundle:Tag t JOIN t.tagset s JOIN s.course c WHERE c.id = ?1')
               ->setParameter('1',$courseid)->getResult();
    }
}