<?php

namespace Marca\HomeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends EntityRepository
{
    public function findPageByType($type)
    {
        $repository = $this->getEntityManager()->getRepository('MarcaHomeBundle:Page');

        $query = $repository->createQueryBuilder('p')
            ->where('p.type = :type')
            ->setParameter('type', $type)
            ->getQuery();

        return $query->getResult();
    }
}